# Generated by Django 4.2 on 2023-07-31 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_bookinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={},
        ),
    ]
