# Generated by Django 4.2 on 2023-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='updated_at',
            new_name='Updated_at',
        ),
    ]
