# Generated by Django 4.2 on 2023-07-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0002_rename_updated_at_bloginfo_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'ordering': ('Updated_at',)},
        ),
    ]
