# Generated by Django 4.2 on 2023-07-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0003_alter_bloginfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'ordering': ('-Updated_at',)},
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='Content',
            field=models.CharField(default='data', max_length=70),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='Title',
            field=models.CharField(default='data', max_length=30),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
