# Generated by Django 4.2 on 2023-08-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, default=None, upload_to='videos')),
                ('amenities', models.ManyToManyField(to='Homeonline.amenitiesmodel')),
            ],
        ),
    ]
