# Generated by Django 4.2 on 2023-08-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseOwnerName', models.CharField(max_length=30)),
                ('Area', models.IntegerField()),
                ('Contactno', models.BigIntegerField()),
                ('BHK', models.IntegerField()),
                ('Status', models.CharField(choices=[('SELL', 'SELL'), ('RENT', 'RENT')], max_length=10)),
                ('Upload_Image', models.ImageField(upload_to='images')),
                ('House_Description', models.TextField()),
                ('House_address', models.TextField()),
                ('House_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_Amenities', models.CharField(max_length=50)),
                ('video_file', models.FileField(upload_to='videos')),
                ('Saler_InfoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo')),
            ],
        ),
    ]
