# Generated by Django 4.2 on 2023-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0002_salerinfo_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='video_file',
            field=models.FileField(blank=True, default=None, upload_to='videos'),
        ),
    ]
