# Generated by Django 4.2 on 2023-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0003_alter_amenities_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='Add_Amenities',
            field=models.CharField(blank=True, choices=[('BO', 'BalconyOutdoor'), ('KIT', 'Kitchen'), ('TV', 'TvDeckTeni'), ('SR', 'Sunroof'), ('RF', 'RoomConcr'), ('HL', 'Hall'), ('STORE', 'Storer'), ('PARKING', 'Park'), ('TUBE', 'Tubewel'), ('WATER', 'Water '), ('GALLERY', 'Gall'), ('solar', 'Solar'), ('furniture', 'Furniture')], default=None, max_length=50),
        ),
    ]
