# Generated by Django 4.2 on 2023-08-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0003_userselectamenities_saler_infoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectamenities',
            name='Saler_InfoId',
        ),
    ]
