# Generated by Django 4.2 on 2023-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0004_alter_amenities_add_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='Add_Amenities',
            field=models.CharField(blank=True, choices=[('BalconyOutdoor', 'BalconyOutdoor'), ('Kitchen', 'Kitchen'), ('TVDeckTeniss', 'TvDeckTeniss'), ('Sunroof', 'Sunroof'), ('RoomConcret', 'RoomConcret'), ('Hall', 'Hall'), ('Storeroom', 'Storeroom'), ('Parking', 'Parking'), ('Tubewel', 'Tubewel'), ('Water', 'Water'), ('Gallery', 'Gallery'), ('Solar', 'Solar'), ('Furniture', 'Furniture')], default=None, max_length=50),
        ),
    ]
