# Generated by Django 4.2 on 2023-08-28 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0004_remove_userselectamenities_saler_infoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectamenities',
            name='video_file',
        ),
        migrations.CreateModel(
            name='UserUploadVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, default=None, upload_to='videos')),
                ('Saler_InfoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo')),
            ],
        ),
    ]
