# Generated by Django 4.2 on 2023-08-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0005_remove_userselectamenities_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselectamenities',
            name='Saler_InfoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo'),
        ),
    ]
