# Generated by Django 4.2 on 2023-08-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0006_userselectamenities_saler_infoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectamenities',
            name='Saler_InfoId',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo'),
        ),
        migrations.AlterField(
            model_name='useruploadvideos',
            name='Saler_InfoId',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo'),
        ),
    ]
