# Generated by Django 4.2 on 2023-08-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0008_salerinfo_video_file_alter_salerinfo_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectamenities',
            name='Saler_InfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo'),
        ),
    ]
