# Generated by Django 4.2 on 2023-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0009_alter_userselectamenities_saler_infoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiesmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
