# Generated by Django 4.2 on 2023-08-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0010_alter_amenitiesmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_values', models.CharField(max_length=255)),
                ('Saler_InfoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo')),
            ],
        ),
    ]
