# Generated by Django 4.2 on 2023-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0011_userselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselection',
            old_name='selected_values',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='Saler_InfoId',
        ),
        migrations.AddField(
            model_name='salerinfo',
            name='amenities',
            field=models.ManyToManyField(to='Homeonline.userselection'),
        ),
        migrations.DeleteModel(
            name='UserSelectAmenities',
        ),
    ]
