# Generated by Django 4.2 on 2023-08-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeonline', '0012_rename_selected_values_userselection_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeonline.userselection')),
                ('saler_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeonline.salerinfo')),
            ],
        ),
    ]
