# Generated by Django 4.2 on 2023-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='Explaination',
            field=models.TextField(default='null'),
        ),
    ]
