# Generated by Django 4.2 on 2023-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0007_alter_mymodel_explaination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='Explaination',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='nothing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
