# Generated by Django 4.2 on 2023-06-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0008_remove_mymodel_explaination_mymodel_nothing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='nothing',
            new_name='Explaination',
        ),
    ]
