# Generated by Django 4.2.1 on 2023-05-24 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 24, 22, 0, 35, 84485)),
        ),
    ]
