# Generated by Django 4.2.1 on 2023-05-25 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_alter_signupinfo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 25, 12, 34, 30, 281555)),
        ),
    ]
