# Generated by Django 4.2 on 2023-06-26 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lifesure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpolicy',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 26, 12, 40, 24, 305781)),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 26, 12, 40, 24, 309788)),
        ),
    ]
