# Generated by Django 4.2 on 2023-06-26 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lifesure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpolicy',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 26, 17, 23, 41, 221394)),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 26, 17, 23, 41, 225393)),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='totalAmount',
            field=models.IntegerField(default=None),
        ),
    ]
